Bar/Bar/Bar/Controllers/OrderHistoryController.cs
using Bar.Models;
using Bar.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Bar.Controllers
{
    public class OrderHistoryController : Controller
    {
        readonly ApplicationDbContext storeDB = new ApplicationDbContext();

        [Authorize(Roles = "Admin")]
        // GET: OrderHistory
        public ActionResult Index(string sortOrder, int? page)
        {
            //Sorting
            ViewBag.CurrentSort = sortOrder;
            ViewBag.OrderIdSortParm = sortOrder == "OrderId" ? "orderid_desc" : "OrderId";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var orders = from o in storeDB.Orders
                           select o;

            switch (sortOrder)
            { 
                case "orderid_desc":
                    orders = orders.OrderByDescending(o => o.OrderId);
                    break;
                case "date_desc":
                    orders = orders.OrderByDescending(o => o.OrderDate);
                    break;
                case "name_desc":
                    orders = orders.OrderByDescending(o => o.UserName);
                    break;
                default:
                    orders = orders.OrderBy(o => o.OrderId);
                    break;
            }

            //Paging
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(orders.ToPagedList(pageNumber, pageSize));
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id) //get data from DB and pass to viewmodel
        {
            var order = storeDB.Orders
                                     .Single(Orderid => Orderid.OrderId == id);

            var orderDetail = storeDB.OrderDetails
                              .Where(orderdetail => orderdetail.OrderId == id);

            var itemsIdList = (from orderdetail in orderDetail
                               select orderdetail.ItemId).ToList();

            var itemsList = storeDB.Items
                              .Where(t => itemsIdList.Contains(t.ID));

            OrderLookupViewModel viewModel = new OrderLookupViewModel();
            viewModel.Order = order;
            viewModel.OrderDetails = orderDetail.ToList();
            viewModel.ItemsList = itemsList.ToList();
            return View(viewModel);

        }
    }
}

Bar/Bar/Bar/Views/OrderHistory/Details.cshtml
@model Bar.ViewModels.OrderLookupViewModel

@{
    ViewBag.Title = "Order History Details";
}

    <p>
        <h3><b>Order ID: @Model.Order.OrderId</b></h3>
        <h3>Order Date: @Model.Order.OrderDate</h3>
    </p>

        <table class="table dt-responsive">
            <tr>
                <th>
                    Item
                </th>
                <th>
                    Price (Each)
                </th>
                <th>
                    Quantity
                </th>
            </tr>


            @foreach (var item in Model.ItemsList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Model.OrderDetails.Where(t => t.ItemId == item.ID).FirstOrDefault().Quantity
                    </td>
                </tr>
            }

        </table>

        <a href="@Url.Action("Index", "OrderHistory")" class="btn btn-default">
            Return to History Index
            <span class="glyphicon glyphicon-tree-deciduous" aria-hidden="true"></span>
        </a>

Bar/Bar/Bar/Views/OrderHistory/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<Bar.Models.Order>

@{
    ViewBag.Title = "Order History";
}

<h2>Order History</h2>

@using (Html.BeginForm())
{
    <p>
        <table class="table dt-responsive">
            <tr>
                <th>
                    @Html.ActionLink("OrderID", "Index", new { sortOrder = ViewBag.OrderIdSortParm })
                </th>
                <th>
                    @Html.ActionLink("OrderDate", "Index", new { sortOrder = ViewBag.DateSortParm })
                </th>
                <th>
                    @Html.ActionLink("UserName", "Index", new { sortOrder = ViewBag.NameSortParm })
                </th>
            </tr>

            @foreach (var order in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => order.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => order.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => order.UserName)
                    </td>
                    <td>
                        <a href="@Url.Action("Details", "OrderHistory", new { id = order.OrderId })" class="btn btn-default">
                            Details
                            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
            }
        </table>
    </p>
}

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort }))