Bar/Bar/Bar/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bar.Models;

namespace Bar.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        [AllowAnonymous]
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))     //Show all items when logged in as "Admin" role
            {
                return View(db.Items.ToList());
            }
            else
            {                               //Show only un-hidden items
                return View(db.Items.Where(i => i.HiddenTag == false).ToList());
            }
        }

        // GET: Items/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ImageUrl,Name,Genre,Price,Description,HiddenTag")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ImageUrl,Name,Genre,Price,Description,HiddenTag")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bar/Bar/Bar/Controllers/OrderLookupController.cs
using Bar.Models;
using Bar.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Bar.Controllers
{
    public class OrderLookupController : Controller
    {
        readonly ApplicationDbContext storeDB = new ApplicationDbContext();
        // GET: OrderLookup

        public ActionResult Index(int? searchid)

        {
            if (searchid.HasValue) //do nothing when sumbit empty input
            {
                try                //try to match record from db with orderID
                {
                    var order = storeDB.Orders
                                     .Single(Orderid => Orderid.OrderId == searchid);

                        var orderDetail = storeDB.OrderDetails
                                         .Where(item => item.OrderId == order.OrderId);

                        var itemsIdList = (from a in orderDetail
                                           select a.ItemId).ToList();

                        var itemsList = storeDB.Items
                                          .Where(t => itemsIdList.Contains(t.ID));

                        OrderLookupViewModel viewModel = new OrderLookupViewModel();
                        viewModel.Order = order;
                        viewModel.OrderDetails = orderDetail.ToList();
                        viewModel.ItemsList = itemsList.ToList();

                        return View(viewModel);
                    
                }

                catch (Exception)
                                    //when fail to match any record
                                    //show "not found" message beside search button
                {
                    ViewBag.result = "not found";
                    return View();
                }

            }
            return View();
        }
    }
}

Bar/Bar/Bar/Views/Shared/Error2.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}

<h1 class="text-danger">Error2.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

Bar/Bar/Bar/Views/Shared/_Layout.cshtml
<script src="/Scripts/jquery-3.4.1.min.js"
        type="text/javascript"></script>
<script type="text/javascript">
    var changeFontSize = function (increaseFont) {
    var fontTargets = new Array('html', 'p');

    fontTargets.forEach(function (element) {
        var $element = $(element);
        var newFontSize;
        var currentFontSize = $element.css('font-size');
        var currentFontSizeNum = parseFloat(currentFontSize, 10);

        if (increaseFont) {
            $element.css('font-size', 10);
            newFontSize = currentFontSizeNum * 1.2;
        } else {
            newFontSize = currentFontSizeNum * 0.8;
        }

        $element.css('font-size', newFontSize);
    });
};
$(document).ready(function () {
    // Reset Font Size
    var originalFontSize = $('html').css('font-size');

    $(".resetFont").click(function () {
        $('html').css('font-size', originalFontSize);
    });
    // Increase Font Size
    $(".increaseFont").on('click', function () {
        changeFontSize(true);
    });
    // Decrease Font Size
    $(".decreaseFont").on('click', function () {
        changeFontSize(false);
    });
});
</script>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ISAD251</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("I S A D 2 5 1", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <a href="@Url.Action("Index", "Home")" class="btn btn-default">
                        Home
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                    </a>
                    <a href="@Url.Action("Index", "Items")" class="btn btn-default">
                        Menu
                        <span class="glyphicon glyphicon-apple" aria-hidden="true"></span>
                    </a>
                    <a href="@Url.Action("Index", "ShoppingCart")" class="btn btn-default">
                        Cart
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                    </a>
                    <a href="@Url.Action("Index", "OrderLookup")" class="btn btn-default">
                        OrderLookup
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </a>
                    <div class="btn-group" role="group" aria-label="...">
                        <h4><span class="label label-default">FontSize:</span></h4>
                        <button type="button" class="increaseFont">+</button>
                        <button type="button" class="decreaseFont">-</button>
                    </div>
                    @if (User.IsInRole("Admin"))
                    {
                        <a href="@Url.Action("Index", "OrderHistory")" class="btn btn-default">
                            OrderHistory
                            <span class="glyphicon glyphicon-tree-deciduous" aria-hidden="true"></span>
                        </a>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>